name: pac
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.6+1

environment:
  sdk: ">=3.0.0-437.0.dev <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  badges: ^3.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_snake_navigationbar: ^0.6.1
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  json_annotation: ^4.8.0
  location: ^6.0.2
  path_provider: ^2.0.13
  pretty_qr_code: ^3.0.0
  provider: ^6.0.5
  readmore: ^3.0.0
  rename: ^3.0.1
  rflutter_alert: ^2.0.7
  rut_utils: ^0.1.2
  shared_preferences: ^2.0.13
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^24.2.8
  url_launcher: ^6.1.14
  # flutter_native_splash: ^2.2.18

dev_dependencies:
  build_runner: ^2.1.11
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo_sin_fondo.png"
  android: true
  ios: true
  web: false
  fullscreen: true
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
